### ISSUE TITLE
python 3 unit test failing on travis (2)

### ISSUE THREAD

**Issue by tdiethe** [IRC-SPHERE/HyperStream#16]
Logging output

```
INFO:root:New workflow created with id test_save_workflow
INFO:root:Added node with id ticker containing 1 streams
INFO:root:Added factor with tool Clock(first=datetime.datetime(1, 1, 1, 0, 0, 0, 0, tzinfo=UTC, stride=1.0) 
INFO:root:Added workflow test_save_workflow to workflow manager
INFO:root:Plate T1 not found for deletion
INFO:root:Meta data test_3.nested_test_A deleted
INFO:root:Meta data test_2.nested_test_D deleted
INFO:root:Meta data test_2.nested_test_C deleted
INFO:root:Meta data test_2.nested_test_B deleted
INFO:root:Meta data test_2.nested_test_A deleted
INFO:root:Meta data test_1.nested_test_D deleted
INFO:root:Meta data test_1.nested_test_C deleted
INFO:root:Meta data test_0.nested_test_C deleted
INFO:root:Meta data test_0.nested_test_B deleted
INFO:root:Meta data test_0.nested_test_A deleted
INFO:root:Plate T.U deleted
INFO:root:Meta data test_3 deleted
INFO:root:Meta data test_2 deleted
INFO:root:Meta data test_1 deleted
INFO:root:Meta data test_0 deleted
INFO:root:Plate T deleted
INFO:root:Meta data test_overlap_3 deleted
INFO:root:Meta data test_overlap_2 deleted
INFO:root:Meta data test_overlap_1 deleted
INFO:root:Meta data test_overlap_0 deleted
INFO:root:Plate V deleted
======================================================================
ERROR: test_new_api_overlapping_plates (tests.test_workflows.HyperStreamWorkflowTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/IRC-SPHERE/HyperStream/tests/test_workflows.py", line 151, in test_new_api_overlapping_plates
    w.execute(time_interval)
  File "/home/travis/build/IRC-SPHERE/HyperStream/hyperstream/workflow/workflow.py", line 89, in execute
    factor.execute(time_interval)
  File "/home/travis/build/IRC-SPHERE/HyperStream/hyperstream/factor/factor.py", line 172, in execute
    alignment_stream=self.get_alignment_stream(None, None))
  File "/home/travis/build/IRC-SPHERE/HyperStream/hyperstream/tool/tool.py", line 78, in execute
    sources=sources, alignment_stream=alignment_stream, interval=interval):
  File "plugins/example/tools/dummy/2017-06-16_v1.0.0.py", line 36, in _execute
    for d in data:
  File "/home/travis/build/IRC-SPHERE/HyperStream/hyperstream/stream/stream_view.py", line 58, in __iter__
    self.stream.parent_node.factor.execute(interval)
  File "/home/travis/build/IRC-SPHERE/HyperStream/hyperstream/factor/factor.py", line 156, in execute
    if list(sorted(itertools.chain(*[s.plates for s in self.sources]))) == self.plates:
TypeError: '<' not supported between instances of 'Plate' and 'Plate'
```

**Comment by tdiethe** [comment]
Now fixed (using plate_id instead of Plate)
