### ISSUE TITLE
sporadic failure of python 2 unit test (always on travis)

### ISSUE THREAD

**Issue by tdiethe** [IRC-SPHERE/HyperStream#19]
logging output:

```
======================================================================
ERROR: test_new_api_overlapping_plates (tests.test_workflows.HyperStreamWorkflowTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/IRC-SPHERE/HyperStream/tests/test_workflows.py", line 151, in test_new_api_overlapping_plates
    w.execute(time_interval)
  File "/home/travis/build/IRC-SPHERE/HyperStream/hyperstream/workflow/workflow.py", line 89, in execute
    factor.execute(time_interval)
  File "/home/travis/build/IRC-SPHERE/HyperStream/hyperstream/factor/factor.py", line 172, in execute
    alignment_stream=self.get_alignment_stream(None, None))
  File "/home/travis/build/IRC-SPHERE/HyperStream/hyperstream/tool/tool.py", line 78, in execute
    sources=sources, alignment_stream=alignment_stream, interval=interval):
  File "plugins/example/tools/dummy/2017-06-16_v1.0.0.py", line 36, in _execute
    for d in data:
  File "/home/travis/build/IRC-SPHERE/HyperStream/hyperstream/stream/stream_view.py", line 58, in __iter__
    self.stream.parent_node.factor.execute(interval)
  File "/home/travis/build/IRC-SPHERE/HyperStream/hyperstream/factor/factor.py", line 167, in execute
    raise NotImplementedError
NotImplementedError: 
```

**Comment by tdiethe** [comment]
Haven't seen this come up in the last few builds ... weird
